# Generated by Django 2.0.1 on 2018-04-26 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BaseAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Подпищик', 'verbose_name_plural': 'Подпищики'},
        ),
    ]
