# Generated by Django 2.0.1 on 2018-04-27 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180427_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='price_per_item',
        ),
    ]
