# Generated by Django 2.0.1 on 2018-04-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180427_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='price',
            new_name='price_per_item',
        ),
    ]
