# Generated by Django 2.0.1 on 2018-04-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180427_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinorder',
            old_name='quantiti',
            new_name='nmb',
        ),
    ]
